version: '3'
services:
    mysql:
        image: mysql:5.7
        container_name: dictionary
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode=""
        environment:
            MYSQL_ROOT_PASSWORD: 1
            MYSQL_DATABASE: test
            MYSQL_USER: admin
            MYSQL_PASSWORD: 1
            LANG: C.UTF-8
        volumes:
            - db_data:/var/lib/mysql
        ports: 
            - "3307:3306"

volumes:
    db_data: 
        driver: local